# Generated by Django 4.0.4 on 2022-05-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=0, upload_to='recipes/imagens/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
